language: python
python:
  - "3.6"

services:
  - docker

before_script: pip install docker-compose

script:
- docker-compose app --rm web sh -c "python manage.py makemigrations && python manage.py migrate && gunicorn mydjango.wsgi -b 0.0.0.0:8000"